#### Numpy - Array 

In [43]:
import numpy as np
num = np.array([56, 33, 12, 78, 52, 68, 25])


In [3]:
type(num)

numpy.ndarray

In [4]:
print(num)


[56 33 12 78 52 68 25]


In [5]:
num.dtype


dtype('int32')

In [6]:
dtype=int(16)

In [7]:
num.dtype


dtype('int32')

In [8]:
num[5]

68

In [9]:
num[5]=61

In [10]:
num

array([56, 33, 12, 78, 52, 61, 25])

In [11]:
num.ndim # Dimension


1

In [12]:
num.min()

12

In [13]:
num.max()

78

In [14]:
num.mean()

45.285714285714285

In [19]:
num1 = np.array([45.4, 58.9, 23.67, 90.9])
num1.dtype

dtype('float64')

In [21]:
num1.sort()
num1

array([23.67, 45.4 , 58.9 , 90.9 ])

In [22]:
num *2

array([112,  66,  24, 156, 104, 122,  50])

In [23]:
num[num > 40] # Conditional Filter

array([56, 78, 52, 61])

In [24]:
num[num < 50]

array([33, 12, 25])

#### Two Dimensional Array

In [26]:
M = np.array([[5,6,7],[2,3,4],[1,2,3]]) ## Array of Array
M

array([[5, 6, 7],
       [2, 3, 4],
       [1, 2, 3]])

In [27]:
M.ndim #Dimension

2

In [28]:
M.shape 


(3, 3)

In [29]:
M.size #No. of Elements

9

In [30]:
M[0,1] # Value in position

6

In [31]:
M[0,1] = 7
M

array([[5, 7, 7],
       [2, 3, 4],
       [1, 2, 3]])

In [33]:
M.T

array([[5, 2, 1],
       [7, 3, 2],
       [7, 4, 3]])

In [34]:
M.transpose()

array([[5, 2, 1],
       [7, 3, 2],
       [7, 4, 3]])

In [36]:
M.reshape(3,3)

array([[5, 7, 7],
       [2, 3, 4],
       [1, 2, 3]])

In [37]:
M.flatten()

array([5, 7, 7, 2, 3, 4, 1, 2, 3])

In [38]:
M.reshape(9)

array([5, 7, 7, 2, 3, 4, 1, 2, 3])

In [40]:
M.reshape(-1,3)

array([[5, 7, 7],
       [2, 3, 4],
       [1, 2, 3]])